# Generated by Django 5.0.6 on 2024-06-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hosp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="specialty",
            new_name="specialization",
        ),
        migrations.AddField(
            model_name="doctor",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="phone",
            field=models.CharField(default=1, max_length=15),
        ),
    ]
